from flask import Flask, request, jsonify, send_file, render_template, send_from_directory
from flask_httpauth import HTTPTokenAuth
import atexit
from typing import Dict
import os
import threading
import pdb
import base64
import tempfile
import datetime
from werkzeug.utils import secure_filename
from Summarize import GeminiSummarizer, genai, query_history
from tokens import tokens


app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'uploads'
auth = HTTPTokenAuth(scheme='Bearer')


# In-memory storage for active conversations
active_conversations = {db: {} for db in tokens.values()}
active_conversations_lock = threading.Lock()

# Load the API key
genai.configure(api_key=os.getenv('GEMINI_API_KEY'))

@auth.verify_token
def verify_token(token):
    if token in tokens:
        return tokens[token]
    return None

def save_uploaded_file(file):
    filename = secure_filename(file.filename)
    file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    file.save(file_path)
    return file_path

def save_cookies(request):
    """Decodes 'key=value;' cookie string from the 'yt-cookies' header, 
    converts it to Netscape format, and saves to a temporary file."""
    encoded_cookies = request.headers.get('yt-cookies')
    if not encoded_cookies:
        return None

    try:
        # Decode the base64 string to the 'key=value; key2=value2' format
        decoded_string = base64.b64decode(encoded_cookies).decode('utf-8')

        # Define the secure flag mapping based on cookies.tsv
        secure_flag_map = {
            'APISID': 'FALSE',
            'HSID': 'FALSE',
            'SID': 'FALSE',
            'SIDCC': 'FALSE'
        }

        # Calculate the expiration timestamp for one hour from now
        expiration_time = int((datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=1)).timestamp())

        # Start building the Netscape cookie file content
        netscape_content = ["# Netscape HTTP Cookie File", "# Generated by GeminiSummarize backend\n"]

        # Parse the cookie string
        cookies = decoded_string.split(';')
        for cookie in cookies:
            if '=' not in cookie:
                continue
            
            name, value = cookie.split('=', 1)
            name = name.strip()
            value = value.strip()

            # Determine the secure flag, defaulting to TRUE
            secure_flag = secure_flag_map.get(name, 'TRUE')

            # Construct the Netscape format line
            # [domain, flag, path, secure, expiration, name, value]
            line = [
                '.youtube.com',       # Domain
                'TRUE',                # Flag (Allow subdomains)
                '/',                   # Path
                secure_flag,           # Secure
                str(expiration_time),  # Expiration
                name,                  # Name
                value                  # Value
            ]
            netscape_content.append("\t".join(line))

        # Create a temporary file and write the content
        with tempfile.NamedTemporaryFile(mode='w+', delete=False, suffix='.txt', encoding='utf-8') as temp_file:
            temp_file.write("\n".join(netscape_content))
            return temp_file.name
            
    except Exception as e:
        print(f"Error decoding or saving cookies: {e}")
        return None

@app.route('/conversations', methods=['POST'])
@auth.login_required
def create_conversation():
    if request.files:
        data = {k:v for k,v in request.form.items()}
        data.update({k:v == 'true' for k,v in data.items() if v.lower() in ['true', 'false']})
        data['files'] = [save_uploaded_file(f) for f in request.files.getlist('files')]
    else:
        data = request.json

    cookie_file = save_cookies(request)
    if cookie_file:
        data['cookies'] = cookie_file
    
    data['db'] = auth.current_user()
    summarizer = GeminiSummarizer(**data)
    with active_conversations_lock:
        active_conversations[data['db']][summarizer.id] = summarizer
    summarizer.save()
    
    return jsonify({"conversation_id": summarizer.id}), 201

@app.route('/conversations', methods=['GET'])
@auth.login_required
def list_conversations():
    offset = int(request.args.get('offset', 0))
    limit = int(request.args.get('limit', 10))
    query_db = request.args.get('db') == 'true'
    filtering = request.args.get('filtering', None)

    if query_db:
        conversations = [e.dict for e in query_history(offset, limit, filtering, db=auth.current_user())]
    else:
        with active_conversations_lock:
            conversations = [v.dict for v in active_conversations[auth.current_user()].values()]
        if filtering:
            conversations = filter(lambda e: filtering in "\n".join(e['urls'] + e['files'] + list(e['ready_files'].values())), conversations)
        conversations = sorted(conversations, key=lambda e: e['timestamp'], reverse=True)[offset:offset+limit]
    return jsonify(conversations), 200

@app.route('/conversations/<conversation_id>', methods=['PUT'])
@auth.login_required
def save_conversation(conversation_id):
    with active_conversations_lock:
        summarizer = active_conversations[auth.current_user()].get(conversation_id)
    if summarizer:
        summarizer.save()
        active_conversations[auth.current_user()].pop(conversation_id)
        return jsonify({"message": f"Conversation {conversation_id} saved successfully"}), 200
    else:
        return jsonify({"error": "Conversation not found"}), 404

def get_summarizer(conversation_id, cache=False):
    with active_conversations_lock:
        summarizer = active_conversations[auth.current_user()].get(conversation_id, GeminiSummarizer(id=conversation_id, db=auth.current_user()))
    if summarizer.history:
        if cache and conversation_id not in active_conversations[auth.current_user()]:
            active_conversations[auth.current_user()][conversation_id] = summarizer
        return summarizer
    else:
        return None
    
@app.route('/conversations/<conversation_id>', methods=['GET'])
@auth.login_required
def get_conversation(conversation_id):
    summarizer = get_summarizer(conversation_id)
    if not summarizer:
        return jsonify({"error": "Conversation not found"}), 404
    
    return summarizer.dict, 200

@app.route('/conversations/<conversation_id>', methods=['DELETE'])
@auth.login_required
def delete_conversation(conversation_id):
    with active_conversations_lock:
        summarizer = active_conversations[auth.current_user()].pop(conversation_id, GeminiSummarizer(id=conversation_id, db=auth.current_user()))

    if summarizer.history:
        summarizer.delete()
        return '', 204
    else:
        return jsonify({"error": "Conversation not found"}), 404

@app.route('/conversations/<conversation_id>/messages', methods=['POST'])
@auth.login_required
def send_message(conversation_id):
    summarizer = get_summarizer(conversation_id, cache=True)
    if not summarizer:
        return jsonify({"error": "Conversation not found"}), 404
    
    message = request.json.get('message')
    if not message:
        return jsonify({"error": "Message is required"}), 400
    else:
        print(message)
    
    response = summarizer.send(message)
    return jsonify({"response": response})

@app.route('/conversations/<conversation_id>/json', methods=['GET'])
@auth.login_required
def get_conversation_json(conversation_id):
    summarizer = get_summarizer(conversation_id)
    if not summarizer:
        return jsonify({"error": "Conversation not found"}), 404
    
    return jsonify(summarizer.json)

@app.route('/conversations/<conversation_id>/markdown', methods=['GET'])
@auth.login_required
def get_conversation_markdown(conversation_id):
    summarizer = get_summarizer(conversation_id)
    if not summarizer:
        return jsonify({"error": "Conversation not found"}), 404
    
    return summarizer.markdown, 200, {'Content-Type': 'text/markdown'}

@app.route('/')
@app.route('/index.html')
def index():
    urls = request.args.get('urls', '')
    prompt = request.args.get('prompt', '')
    return render_template('index.html', urls=urls, prompt=prompt)

@app.route('/manifest.json')
def manifest():
    return send_file('statics/manifest.json')

@app.route('/favicon.ico')
def favicon():
    return send_file('statics/favicon.ico')

@app.route('/statics/<filename>')
def statics(filename):
    return send_from_directory('statics/', filename)

def save_active_conversations():
    for db in active_conversations:
        for summarizer in active_conversations[db].values():
            summarizer.save()

atexit.register(save_active_conversations)

if __name__ == '__main__':
    app.run(debug=True, host="0.0.0.0")