#!/bin/bash

set -ex

SCRIPT_PATH=$(dirname $(realpath "$0"))
source $SCRIPT_PATH/env/bin/activate

extra_args=${extra_args:-}
model=${lang:-models/gemini-1.5-flash}

export http_proxy=http://127.0.0.1:8118 
export https_proxy=http://127.0.0.1:8118 

python3 $SCRIPT_PATH/Summarize.py --file "$1" --model $model --question --save_history $extra_args
